# Use the official Python image from the Docker Hub
FROM python:3.13-slim

# Set the working directory
WORKDIR /app

# # Copy the current directory contents into the container at /app
# COPY . /app

COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# ------------------------------------------------------------------------
COPY .github/ .github/

COPY configs/ configs/

COPY src/ src/

COPY outputs/ outputs/
# ------------------------------------------------------------------------    

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches, and make sure the streamlit app is accessible from your device outside the container
CMD ["streamlit", "run", "src/app.py", "--server.address=0.0.0.0"]