seed: 42
img_size: 128
batch_size: 8
num_workers: 2
lr: 0.0003
epochs: 1
use_focal: false
focal_gamma: 1.0
use_class_weights: true
device: auto
data_path: data/wafer_maps.pkl
train_data_path: data/wafer_train_unittest.pkl
test_data_path: data/wafer_test_unittest.pkl
out_dir: outputs/test_output